---
title: "Express.js"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

Az Express.js egy Node.js alapú back-end JavaScript framework, amely megkönnyíti webalkalmazások és API-k létrehozását. A MERN és MEAN stack része, az egyik legnépszerűbb JS framework. Jelentősen megkönnyíti a Node.js-ben végezhető műveletek (pl. routing, templating) programozását.

## Telepítés és használat

Az express.js-t node projektekhez telepíthetjük az `npm install express` paranccsal. Ezután a szokásos módon, a `require('express')` paranccsal importálhatjuk. A return érték egy függvény, amellyel létrehozható az alkalmazás, amely számos hasznos property-vel és metódussal rendelkezik. Ezek között van például a `.listen`, amivel egyszerűen elindíthatjuk a web szervert. 

```{js}
const express = require('express');

const app = express();

app.listen(3000);
```

Jó gyakorlat a szervert külön file-ban kezelni, és így lesz egy app file, amelyben létrehozzuk az applikációt az összes middleware-rel (ld, később), amelyből exportáljuk az applikációt, és egy server file, amelybe importáljuk az applikációt, és itt indítjuk el a szervert a `.listen` metódussal.

```{js}
const app = require('./app');

const port = 3000;
app.listen(port, () => {
  console.log(`App running on port ${port}...`);
});
```

## Middleware-ek használata

Általánosan middleware függvényeknek nevezzük azokat a függvényeket, amelyeknek hozzáférésük van a request és response objektumokhoz és a next middleware függvényhez. Az Express alkalmazás sokszor ilyenekből épül fel, amelyek a különböző requestek esetében futnak, és módosítják a request és response objektumokat. A request több ilyen middleware-en megy keresztül, amíg megszületik a response. 

Az ezek által végzett tevékenységek lehetnek:  

1. Valamilyen kód futtatása.
2. A request és response objektumok módosítása: adatok kiolvasása, küldése, státusz módosítása, stb.
3. A request-response ciklus lezárása.
4. A következő middleware függvény hívása.

A middleware-ek összességét nevezzük Middleware Stack-nek, és ezek olyan sorrendben lépnek működésbe, ahogy a programfile-ban megadtuk ezeket.

Middleware-eket az app `.use()` vagy valamelyik `.METHOD` metódussal (get, post, put, stb.) is létrehozhatunk. Előbbi minden típusú requestet kezel, míg utóbbiak csak a megfelelő metódusúakat. A `.use()` kaphat útvonal argumentumot is, de nem szükséges. Ha nem kap, akkor minden requestre lefut, amely eléri (Ha korábbi middleware lezárta a request-response ciklust, akkor nem éri el).

Fontos különbség a `.use()` és a többi metódus között, hogy a megadott útvonal a `.use()` esetében nem csak pontos egyezést jelenthet, hanem bármit, ami így kezdődik.

Ha egy middleware-ben nem zárjuk le a request-response ciklust (pl. `.send()`-del), akkor a `next()` függvénnyel át kell adnunk a kezelést a következő middleware-nek. A request-response ciklust le kell zárni az utolsó middleware-ben, amelyen egy adott request keresztülmegy. 

### Request és response objektum

A middleware függvény hozzáférést kap a request és response objektumokhoz, amelyek kicsit különböznek a Node.js alap objektumaitól. A res objektum `.send()` metódusával küldhetünk html-ben írt választ, a `.json()` metódus pedig JSON formátumúra kódolja a JS objektumokat, és mindkettő egyúttal beállítja a megfelelő content-type-ot is. A státuszt a `.status()` metódussal adhatjuk meg, és a metódusok láncba fűzhetők. A `.redirect()` metódussal átirányíthatjuk a requestet egy másik URL-re.

Egyszerre több callback függvény is megadható, de ebben az esetben a next() függvénnyel lehetővé kell tenni, hogy a következő függvény átvegye a route kezelését.

```{js}
app.get('/', (req, res) => {
  res
    .status(200)
    .json({ message: 'Hello from the server side!', app: 'Natours' }); // auto set content-type
});

app.post('/', (req, res) => {
  res.send('Data sent.');
});

app.get('/abc', (req, res, next) => {
  ...
  next()
}, (req, res) => {
  ...
})
```

### Mások által írt middleware függvények

Ilyen például a body-parser `.urlencoded()`, illetve `.json()` metódusa. Előbbi az elküldött form adatokat tudja kiolvasni a `request.body`-ból, utóbbi pedig a JSON formátumban küldött adatokat teszi elérhetővé.

Ezek jelenleg az Express (v14) részei is, így az express objektumon is megtalálható metódusok.

```{js}
app.use(bodyParser.urlencoded({ extended: false }));

// app.use(express.urlencoded({ extended: false }));
app.use(express.json());
```

Ilyen middleware a morgan csomag is, amely egy függvényt tesz elérhetővé fő exportként, amely arra szolgál, hogy a requesteket logoljuk.

```{js}
const morgan = require('morgan');

app.use(morgan('dev'));
```

Ezeknek a függvényeknek return értékei szokásos felépítésű middleware függvények: argumentumai a request és response objektum, illetve a next függvény, amelyet a végén hívnak, hogy a request kezelését a következő middleware-nek adják át. 

```{js}
function middlewareName (req, res, next) {

  // ...
  
  next()
}
```

Az elérhető Express middleware-ek listája megtalálható az Express.js [honlapján is](https://expressjs.com/en/resources/middleware.html).

### Middleware chaining

Egy route-hoz több middleware függvény is megadható. A megadott middleware-eket vesszővel elválasztva adhatjuk meg. Ezzel például ellenőrizhetjük, hogy a felhasználó rendelkezik a szükséges jogokkal, az elküldött adatok tartalmazzák a szükséges információkat, és csak ezután kezeljük a kapott adatokat.

```{js}
router.post(tourController.checkBody, tourController.createTour);
```

## Routing

A routing egyrészt egyszerűsödik azáltal, hogy az app objektumnak minden http metódushoz kapcsolódóan van megfelelő metódusa, illetve a use metódus minden http requestet kezelni tud. Másrészt, az Express Router lehetővé teszi a routing logika külön file-okban való tárolását, és importálását a fő file-ba.

Ehhez az app file-ben vagy külön file-okban router objektumokat hozunk létre, amelyeken regisztráljuk a megfelelő middleware függvényeket a megfelelő metódusokhoz és útvonalakhoz. A router objektumon létrehozhatók ugyanúgy a use, get, post, stb. metódusok, ugyanolyan szintaxissal. 

A különbség, hogy ez importálható lesz, és így nem kell egy file-ban létrehozni ezeket. Arra viszont figyelni kell, hogy minden ugyanúgy működik majd, mintha a fő file-ban lennének, tehát pl. figyelni kell a megfelelő sorrendre, hogy jól kezeljük a különböző útvonalakat.

Az importálás után az `app.use()` metódussal regisztrálhatjuk a router middleware-eket. 

```{js}
// admin.js
const express = require('express');

const router = express.Router();

router.get('/add-product', (req, res, next) => {
  res.send(
    '<form action="/product" method="POST"><input type="text" name="title"><button type="submit">Add product</button></form>'
  );
});

router.post('/product', (req, res, next) => {
  console.log(req.body);
  res.redirect('/');
});

module.exports = router;

// app.js
const adminRoutes = require('./routes/admin');
const shopRoutes = require('./routes/shop');

// ...

app.use(adminRoutes)
app.use(shopRoutes);

// ...
```

Az `app.use()`-ban megadhatunk route-ot, amelyek esetén használni szeretnénk, vagy ezt ki is hagyhatjuk (ld. fent), és akkor minden requestre vonatkozhatnak. Ha viszont megadunk valamilyen route-ot, akkor a router route-jait már csak ehhez képest kell megadni.

```{js}
app.use('/api/v1/tours', tourRouter);

const tourRouter = express.Router();

tourRouter.route('/').get(getAllTours).post(createTour);
tourRouter.route('/:id').get(getTour).patch(updateTour).delete(deleteTour);
```

Nagyobb projektek esetében a jó gyakorlat, hogy a fő .js file-ban csak a különböző middleware-eket regisztráljuk, tehát, hogy milyen requestek esetében milyen routereket használunk. A routerekben definiáljuk a konkrét útvonalakat, külön controller file-okban pedig az ezekhez tartozó handler függvényeket.

### Method chaining

Ha ugyanazon az útvonalon akarunk többféle metódust kezelni, akkor ezeket össze is fűzhetjük. Ugyanez működik a routerrel is.

```{js}
app.route('/api/v1/tours').get(getAllTours).post(createTour);

app
  .route('/api/v1/tours/:id')
  .get(getTour)
  .patch(updateTour)
  .delete(deleteTour);
  
router.route('/products').get(getAllProducts).post(postNewProduct)
```

### Filter

Az Express lehetővé teszi, hogy könnyen kezeljük az összetettebb, ugyanúgy kezdődő route-okat:

```{js}
app.use('/admin', adminRoutes)
```

A fenti middleware akkor fogja kezelni a route-ot, ha az `/admin/valami` formájú. Ezek után az adminRoutes-ban már az `/admin` rész nélkül adjuk meg a route-okat.

A Param middleware-rel megtehetjük, hogy egy middleware-t csak akkor futtatunk, ha a request url egy bizonyos paramétert tartalmaz. Ebben az esetben a handler függvény hozzáfér a szokásosakon kívül a paraméter értékéhez is.

```{js}
router.param('id', (req, res, next, val) => {...})
```

Például használható arra, hogy validáljuk a megadott paramétert egy handler függvényben.

#### Dynamic Routes

Sokszor arra is szükségünk van, hogy a route-ot dinamikusan építsük fel. Ezt használjuk, amikor pl. egy-egy termékről, felhasználóról, stb. akarunk részletes adatokat bemutatni. Ilyenkor az url-be beépítjük a dinamikusan változó részt, amit a programmal ki kell olvasnunk.

Az Express ezt is megkönnyíti a route-ok megadásánál. A dinamikus részt `GET` request esetén egy `:` után adhatjuk meg, és bárhogy elnevezhetjük. Csak arra kell figyelni, hogy a template-ekben is a megfelelő útvonalat adjuk meg a linknek.

Figyelni kell arra, hogy ha vannak olyan route-jaink, amelyek ugyanolyan felépítésűek, de nem dinamikus elemet tartalmaznak, ezek megelőzzék, mert különben ezek soksem élesednének. 

Több paraméter is megadható egymás után, és opcionális paraméterek is lehetségesek (`?`-et írunk mögéjük)

```{js}
app.get('/products/delete', deleteProduct);
app.get('/products/:productId', getProduct);
app.get('/products/:category/:subcat/:id', getProduct);
app.get('/products/:category/:type/:color?', getProduct);
```

A megadott paraméterek az url-ből a `request.params` attribútumon érhetők el, a megadott névvel: pl. `req.params.productId`.

`POST` requestek esetén ezen túl, a request body-ba írhatunk adatokat. Ez történik akkor is, ha egy html form adatait küldjük post requesttel. Ha nem új formról, hanem pl. a kosárhoz adásról van szó, ehhez pl. `type="hidden"` input elemeket használhatunk, amelyekkel az adott termék id-ját továbbítjuk. Az adatot a `req.body.name` property-n érhetjük el, ahol `name` az a név, amit az inputnak adtunk, értéke pedig az lesz, ami az input `value` értéke volt.

#### Query paraméterek

A route-ok dinamikus részein túl query paramétereket is megadhatunk, amelyekkel további adatokat továbbíthatunk. Ezek már nem tartoznak a route-hoz, ezért pl. a routerben nem kell ezekkel foglalkozni, de a controllerekben vagy a route-ok callbackjeiben kinyerhetjük ezeket az adatokat a `req.query.key` módon, ahol a `key` az, amit a url-ben megadtunk.

pl. Ilyen url lehet: `/edit-product/12345?edit=true`, amelyet a `req.query.edit` property-vel érünk el.

Több query paramétert is megadhatunk, ha `&` karaktert teszünk közéjük.

### 404 error page

Kihasználva, hogy a use metódussal akár az összes requestet kezelhetjük, metódustól és útvonaltól függően, ha a kód végére megadunk egy ilyen middleware-t, kezelhetjük a nem létező route-okat is:

```{js}
app.use('/', (req, res, next) => {
  res.status(404).send('<h1>Page not found!</h1>');
});
```

## Html file-ok küldése

res.sendFile() automatikusan felismeri, hogy html file-ról van szó.
A file-okban lévő linkeket is a szerver által kezelt routoknak megfelelő útvonalakkal kell lecserélni: "restaurants.html" helyett "/restaurants" - fontos a "/", mert így abszolút útvonalak lesznek, és közvetlenül a domain-név után ez jön.
A css és js file-okkal való kapcsolat így elveszik - ennek javításához egyrészt javítani kell a linkek útvonalait, másrészt explicite kezelni kell az ezeknek megfelelő requesteket. Mivel ez nagyon munkaigényes lenne, az express-nek van erre szolgáló eszköze: 

```{js}
// Serving static (css, js) files
// app.use(express.static(foldername))
app.use(express.static(path.join(__dirname, 'public')));
```

A public mappán belül lehetnek almappák. A file-okra mutató linkekben a "public" mappát már el kell hagyni, csak ezen belül kell megadni az útvonalat.
Ez a többi route elé kerül, és ha a request statikus file-ra vonatkozik, amely a megadott mappában található, akkor ezzel kezeli, ha nem, akkor a később megadott route-okkal.

### Útvonalak

A file-okra vonatkozó útvonalak felépítéséhez hasznos a `path` könyvtár. Ennek a join metódusa lehetővé teszi az útvonalak felépítését, a dirname metódus pedig egy file mappájának megállapítását, ami felhasználható ahhoz, hogy a root könyvtárat megadjuk.

```{js}
path.join(__dirname, "views", "index.html");

// root mappa
const rootPath = path.dirname(require.main.filename);
// korábban
// const rootPath = path.dirname(process.mainModule.filename);
```

### Templating

Különböző template engine-ek: legnépszerűbb az EJS, de népszerű a Pug és a Handlebars is, és továbbiak is léteznek. Ezeket telepíteni kell a projekthez: `npm install ejs pug express-handlebars`

Ezek után tudatni kell az Express-szel, hogy melyiket szeretnénk használni. Az EJS és a Pug beállítása könnyebb, mert ezeket beépítetten kezeli az Express.

```{js}
// Opcionális, ha a views mappában vannak (ez a default)
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');
// vagy 
app.set('view engine', 'pug');
```

Ha a Handlebars-t szeretnénk használni, azt először importálni kell, majd regisztrálni, mint template engine-t, és csak ezután használható a fenti módon.

```{js}
const expressHbs = require('express-handlebars');

app.engine('hbs', expressHbs());
app.set('view engine', 'hbs');
```

A renderelt file-ok .pug, .hbs (ugyanaz, mint ahogy a programkódban elneveztük) vagy .ejs kiterjesztésű file-ok. Az EJS és a Handlebars normál html-t ötvöz speciális részekkel, míg a pug egy leegyszerűsített szerkezetet használ.

Miután készen vannak a file-ok, a route-okban `sendFile` helyett a `render` metódussal tudjuk ezeket megjeleníteni.

```{js}
res.render('index')
```

A render a beállított alapértelmezett templating engine-t fogja használni.

A renderrel különböző adatokat is továbbíthatun a template-nek, amelyeket felhasználhatunk a template-ben, amelyben elérhetők lesznek az objektumban key-ként megadott változónevek, amelyek az értékként megadott objektumokra hivatkoznak.

```{js}
res.render('product-list', {
  products: allProducts,
  path: '/product-list',
  pageTitle: 'Products',
})
```

#### Pug

A pug szintaxisa az html tag-eket használja, de egy egyszerűsített, indentáláson alapuló szintaxissal. A tagekkel kezdjük a deklarálást, class-okat a "."-tal adhatunk hozzá, id-t pedig "#"-tel. Div megadható a tag nélkül is. Ha szöveges tartalma van a tag-nek, akkor ezt egy szóköz után egyszerűen megadhatjuk. Az attribútumokat "()" közé írjuk. Lezáró tagek nincsenek, és máshogy sem kell lezárni a sorokat.

```{}
h1.main-title This is the Title of the Page
.container
a.btn-link(href="www.google.com") Go to Google.com
```

A pug-ban lehetőség van változó értéket használni, feltételes tartalmat megadni és iterálni:
```{}
h1 #{mainTitle}

ul.friends-list
  if friends.length > 0
    each friend in friends
      li.list-item #{friend.name}
  else
    h3 You have no friends :(
```

Hasznos funkció, hogy layoutokat használhatunk. Ezek az oldalak közös részeit tartalmazzák, plusz olyan blokkokat (pl. `block styles`), amelyeket a részfile-okban kitölthetünk tartalommal.

```{}
doctype html
html(lang="en")
  head
    meta(charset="UTF-8")
    meta(http-equiv="X-UA-Compatible", content="IE=edge")
    meta(name="viewport", content="width=device-width, initial-scale=1.0")
    title #{ pageTitle }
    link(rel="stylesheet", href="/css/main.css")
    block styles 
  body 
    header.main-header
      nav.main-header__nav
        ul.main-header__item-list
          li.main-header__item
            a(href="/") Shop
          li.main-header__item
            a(href="/admin/add-product") Add Product
    block content
```

```{}
extends layouts/main-layout.pug

block content
  h1 Page Not Found!
```

Az osztályokat dinamikusan is megadhatjuk a layoutban JS ternary operator segítségével.

#### Handlebars

A Handlebars is tudja kezelni a feltételes utasításokat, iterálást, illetve layoutokkal is tud dolgozni. A szintaxis a normál html-en alapszik. Változók értékeit egyszerűen behelyettesíthetjük, ha a változó nevét `{{}}` közé írjuk. Az if/else parancsokat és az iterálást is `{{}}` segtségével adhatjuk meg. Az iterálás során a `this` kulcsszó a soron következő elemre utal.

Fontos, hogy ellentétben pl. a puggal, itt a JavaScript logika nem működik a template-ben, hanem ennek a js file-ban kell megtörténnie, a template-nek csak az eredményt továbbíthatjuk, az objektum részeként.
 
```{}
<h1>{{ title }}</h1>

{{#if boolVar}}
  <div>...</div>
{{ else }}
  <p>...</p>
{{/if}}

<ul>
  {{#each arr}}
    <li>this.name</li>
  {{/each}}
</ul>
```

Layoutokat is használhatunk, ehhez a handlebars engine-t konfigurálni kell egy objektummal: a `layoutsDir` a layout file-ok könyvtárát közli, a `defaultLayout` az alapértelmezett layout file-t (kiterjesztés nem kell), az `extname` pedig lehetővé teszi, hogy na az alapértelmezett .handlebars kiterjesztést ismerje csak fel.

```{js}
app.engine(
  'hbs',
  expressHbs({
    layoutsDir: 'views/layouts',
    defaultLayout: 'main-layout',
    extname: 'hbs',
  })
);
```

Ezután létrehozható a layout file, amelyben használhatók a fenti placeholderek, illetve logika. Pl. a nem közös css és js file-ok beillesztése is a fent bemutatott if/else utasítások és boolean változók kombinációjával oldható meg. Változó blokkot csak egyet adhatunk meg a layoutban a `{{{ body }}}` placeholder használatával.

A részfile-okban már csak annak a résznek kell szerepelnie, amelyet a placeholder helyére szeretnénk betenni.

#### EJS

Az ejs bizonyos szempontból a másik kettő keveréke, mivel normál html-t használ (mint a handlebars), amelyekbe placeholderekkel beilleszthetünk nemcsak változó értékeket (mindkettő), hanem JS logikát is (mint a pugban).

Az ejs szintaxis a sima szövegek beillesztéséhez `<%= varName %>`, amellyel beilleszthetjük tagek tartalmát, de attribútumok értékeit is. Html beillesztéséhez `<%- html %>` használható (pl. ezt használhatjuk a layoutokhoz), JS logika pedig `<% %>` közé kerülhet, amelyet le is kell zárni (mint a handlebars-ban). Ide kerülhet if/else, ternary, bármilyen ciklus, stb.

```{}
<h1><%= title %></h1>

<% if (condition) { %>
  <div>...</div>
<% } else { %>
  <p>...</p>
<% } %>

<ul>
  <% for (let friend of friends) { %>
    <li>friend.name</li>
  <% } %>
</ul>
```

A Layout logika helyett, amely szerint a közös részekbe beilleszthetünk dinamikus részeket, az ejs logika fordított, a közös részeket (vagy bármilyen többé-kevésbé önálló komponenst) illeszthetjük be a külön file-okba. 
Html részeket (partial) kiszervezhetünk külön file-okba (tipikusan külön mappába pl. includes névvel), amelyek tartalmát beilleszthetjük. 

Mint az alábbi példában látható, nem is kell, hogy a beillesztett rész önmagban működőképes legyen. Lehet az csak a metaadatokat tartalmazó <head> rész, akár a zárótag nélkül

```{}
<%- include('includes/head.ejs') %>
<link rel="stylesheet" href="site.css">
</head>
```

## Controllerek

Az MVC felépítés jegyében a különböző route-ok *handler* függvényeit külön controller file-okban is tarthatjuk, amelyekből exportáljuk ezeket, és a route-okban az importált függvényeket használjuk callback-ként.

Pl. egy ilyen controller file az alábbi (részlet):

```{js}
const Product = require('../models/product');

exports.getAddProduct = (req, res, next) => {
  // res.sendFile(path.join(rootDir, 'views', 'add-product.html'));
  res.render('admin/add-product', {
    path: '/admin/add-product',
    pageTitle: 'Add Product',
  });
};

exports.postAddProduct = (req, res, next) => {
  const title = req.body.title;
  const imageUrl = req.body.imageUrl;
  const price = req.body.price;
  const description = req.body.description;

  const product = new Product(title, imageUrl, description, price);
  product.save();
  res.redirect('/');
};
```

Ezeket a controller függvényeket a route-okban megadhatjuk az adott route callback-jeként:

```{js}
const express = require('express');

const adminController = require('../controllers/admin');

const router = express.Router();

router.get('/add-product', adminController.getAddProduct);
router.get('/products', adminController.getProducts);
router.post('/add-product', adminController.postAddProduct);

module.exports = router;

```

## Modelek

Az MVC architektúrában az adatokkal a model file-okban dolgozunk. Gyakori, hogy osztályokat hozunk létre a különböző objektumok számára. Ezeknek különböző metódusokat adunk, pl. az adatok beolvasására, új adatok hozzáadására, stb. Az adatok beolvasására szolgálók lehetnek static metódusok, hogy magán az osztályon hívhassuk ezeket, és ne kelljen ezért ál-instanciákat létrehozni.

## File-ba írás

A programkódban tárolt adatok egyik alternatívája, ha file-okkal dolgozunk. Általában JSON file-ba írunk a JSON objektummal. Az objektumot a `JSON.stringify()` metódussal alakítjuk JSON formátummá, fordítva pedig a `JSON.parse()` metódus segítségével tudjuk a JSON szöveget objektummá alakítani.

Ha az olvasás és írás aszinkron módon történik, ami célszerű, ha olyan kódban tesszük, amely az Event loopban fog futni (hogy ne blokkoljuk a futást), megbonyolíthatja a munkát, mert pl. ha a beolvasott adatok alapján szeretnénk renderelni, akkor a kontrollerben nem tudjuk egyszerűen return-ölni a kapott adatokat, mert ezek még nem állnak rendelkezésre, amikor lefut a model megfelelő metódusa.

Az egyik megoldás, hogy egy callback függvény argumentumot adunk a metódusnak, amelyet hív az aszinkron művelet befejezését követően, és amelyet aztán a kontrollerben deklarálni tudunk a metódus hívása során, és ennek a teste lehet pl. az adatok alapján történő renderelés.

Pl. a model file

```{js}
const fs = require('fs');
const path = require('path');

// Csak segéd: a file elérési útvonala
const p = path.join(
  path.dirname(process.mainModule.filename),
  'data',
  'products.json'
);

// Függvénybe kiszervezett file-olvasás az említett callback-kel
// Az aszinkron művelet végén hívja a cb() függvényt
const getProductsFromFile = (cb) => {
  fs.readFile(p, (err, fileContent) => {
    if (err) {
      return cb([]);
    }
    cb(JSON.parse(fileContent));
  });
};

module.exports = class Product {
  constructor(title, imageUrl, description, price) {
    this.title = title;
    this.imageUrl = imageUrl;
    this.description = description;
    this.price = price;
  }

  save() {
    this.id = Math.random().toString();
    // A használat során megadjuk a callback függvényt: ennek argumentuma a produktumk listája (ld. fent)
    getProductsFromFile((products) => {
      products.push(this);
      fs.writeFile(p, JSON.stringify(products), (err) => {
        if (err) console.log(err);
      });
    });
  }

  // Itt csak továbbadjuk: a controller-ben, ahol hívjuk a fetchAll metódust, ott deklaráljuk
  static fetchAll(cb) {
    getProductsFromFile(cb);
  }

  // Ez egy fokkal bonyolultabb, mert egyrészt deklarálunk egy callback-et a getProductsFromFile függvényhez
  // másrészt csak hívjuk, a deklarálás a controllerben történik
  static findById(id, cb) {
    getProductsFromFile((products) => {
      const product = products.find((p) => p.id === id);
      cb(product);
    });
  }
};

```

Pl. a contollerben, amely a termékeket betölti, és egy konkrét terméket is betölt:

A deklarált callback-ek a termékek listáját kapják, és renderelik a megfelelő view-ket.

```{js}
const Product = require('../models/product');

exports.getProducts = (req, res, next) => {
  // res.sendFile(path.join(__dirname, '..', 'views', 'shop.html'));
  const products = Product.fetchAll((products) => {
    res.render('shop/product-list', {
      prods: products,
      pageTitle: 'All Products',
      path: '/products',
    });
  });
};

exports.getProduct = (req, res, next) => {
  const prodId = req.params.productId;
  Product.findById(prodId, (product) => {
    res.render('shop/product-detail', {
      product: product,
      pageTitle: product.title,
      path: '/products',
    });
  });
};

exports.getIndex = (req, res, next) => {
  const products = Product.fetchAll((products) => {
    res.render('shop/index', {
      prods: products,
      pageTitle: 'Shop',
      path: '/',
    });
  });
};
```

## API-k

### REST API design

Ennek légyege, hogy a különböző erőforrásokat URL-ek segítségével tesszük elérhetővé (pl. /tours, /films). Az erőforrások eléréséhez, a CRUD (Create Read Update Delete) tevékenységekhez különböző http metódusokat használunk: olvasáshoz `GET`, új itemhez `POST`, szerkesztéshez `PUT` (teljes objektum kell) vagy `PATCH` (csak módosított részek kellenek), törléshez `DELETE`. Az egyes erőforrásokon belül adhatunk hozzáférést egyes elemekhez. 

Az adatokat jellemzően `json` formátumban küldjük, általában valamilyen módon formázva, pl. egy másik objektumba ágyazva a JSEND módszer szerint. Itt látható egy sikeres és egy sikertelen kérés esetén küldött válasz, JSEND módszer szerint: az objektum tartalmazza a status-t, egy üzenetet, adatokat, illetve, ha több adatot küldünk, tartalmazhatná ennek hosszát is (pl. hány túra, recept, film, stb. van az objektumban).

```{js}
const getTour = (req, res) => {
  const id = req.params.id * 1;
  const tour = tours.find((el) => el.id === id);

  if (!tour) {
    return res.status(404).json({
      status: 'fail',
      message: 'Invalid ID',
    });
  }

  res.status(200).json({
    status: 'success',
    data: {
      tour: tour,
    },
  });
};
```

A RESTful API-k stateless-ek: a state-et a kliens kezeli, a szerver nem emlékezik a korábbi kérésekre ahhoz, hogy a jelenlegi kérést kiszolgálja.

Érdemes az API verzióját is bevenni, hogy ha később változtatunk, a korábbi API-t használók kódja tovább működjön.

Maga a gyakorlati megvalósítás Express-ben nem különbözik jelentősen attól, amikor weboldalakat küldtünk választként, csak annyiban, hogy a válasz json formátumú lesz. Ugyanúgy a különböző route-okat kell kezelni handler függvényekkel.

#### Státuszok
 
Rest API-nál többféle státusz közül szokás válogatni:  
- `404` jelöli, hogy nem találtuk a megadott URL-t (pl. hibás ID esetén)
- `200` jelöli, hogy rendben ment minden (OK), pl. amikor GET vagy PATCH requestet küldünk
- `201` jelöli, hogy valamit sikeresen létrehoztunk (Created), pl. POST request esetén
- `204` jelöli, hogy a válasznak nincs tartalma (No content), pl. DELETE request esetén nem küldünk vissza adatot, csak visszajelzünk, hogy sikeres volt a törlés

## Környezet változók

A Node.js és Express alkalmazások különböző környezetekben futhatnak: legfontosabbak a fejlesztői (*development*) és az éles (*production*) környezet. A környezettől függően lehetséges, hogy más adatbázisokat akarunk használni, illetve más funkciókat akarunk be- vagy kikapcsolni. 

Az environment változók olyan globális változók, amelyek a Node alkalmazás környezetét adják meg. A Node.js maga is sok változót ad meg alapértelmezettként, és az Express is. Alapértelmezettként az Express development environmentként állítja be a környezetet. 

A környezetet a `process.env` property révén (Node.js környezeti változók) és `app.get('env')` (Express környezeti változók) paranccsal kapjuk meg. 

Az Express-ben sok csomag támaszkodik a NODE_ENV változóra (konvenció), amelynek meg kell adnia, hogy milyen módban vagyunk. Ezt manuálisan kell megadni. A `process.env` révén ellenőrizhetők ezek a változók.  

1. A terminálban (több is megadható egymás után): `NODE_ENV=development nodemon server.js`
2. Config file-ban (config.env): VS Code-ban a dotENV kiegészítő hasznos lehet a formázáshoz. A file tartalmához a dotenv csomaggal férhetünk hozzá (npm-ről telepíteni kell), amelynek a `dotenv.config({ path: './config.env' })` paranccsal adjuk meg, milyen file-ban keresse a változók deklarációit.

Elég csak egy modulban beolvasni, és az egész alkalmazás részére elérhető lesz, mert a process core modul részévé válnak. Ennek még az app importálása előtt kell történnie.