---
title: "jQuery"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## jQuery beillesztés

jQuery-t a html file head-jébe beillesztett script taggel tudjuk betölteni.

```{}
<script src="https://code.jquery.com/jquery-3.1.1.js"></script>
```

Minden jQuery parancs `$` jellel (bling) kezdődik.

## Document ready function

Ahhoz, hogy a jQuery script csak az oldal betöltése után fusson, az alábbi függvénybe kell írni:
```{js}
$(document).ready(function() {
  // ide jönnek az utasítások
});
```

Mivel ezt a kódot általánosan használják jQuery scriptekben, rövidített változata is született:
```{js}
$(function() {
   // jQuery code goes here
});
```

## jQuery selectorok

A jQuery hasonlóan a JS-hez elfogadja a szokásos CSS selectorokat:

```{js}
// Universal
$("*")

// Element
$("body")
$("button")

// Class & id
$(".class-name")
$("#id1")

// Traverse
$("#img-author").parent()     // direct parent
$("#img-author").parents()    // all ancestors
$(".container").children()    // direct children
$("#project-1").siblings()
$("#features").next()         // .prev()
$("#features").nextAll()      // .prevAll()
$("div").eq(index)            // element from a list of selected (0-based)

// Pseudo-classes
$("p:first")                  // 1st p element
$("li:last")
$("p:first-child")
$("p:last-child")
$(".class-name:nth-child(2)") // Every 2nd child with given class name of any parent
$(".class-name:even")         // or odd (0-based!)

// Composite
$("div.menu")       // div with class
$("h1, p")          // h1 & p
$("div > p")        // direct child
$("div p")          // all p that are descendants of a div
```

## jQuery parancsok

```{js}
// Create element
const txt = $("<p></p>").text("This is some text in a paragraph.")

// Manipulate classes
$("button").addClass("class-name");
$(".class-name").addClass("new-class another-class");
$("#id1").removeClass("class-name");
$("body").toggleClass("dark-mode")

// Get, set and remove attributes
const url = $("a").attr("href");
$("img").attr("src", "img/1.jpeg")
$("#my-div").removeAttr("border")

// Get and set content or value
const element = $("div").html();
const divText = $("#my-div").text();
$("h3").html("<em>New Heading</em>");
$("h3").text("Only text is changed");
const answer = $("#my-input").val();
$("#email").val("example@mail.com")

// Get and manipulate CSS, properties
alert($(".header").css("background-color"));
$(".introduction").css("color", "blue");
$("#button2").css({"border":"none", "background-color": "blue", "padding": "20px 30px"})
$("#button1").prop("disabled", true);
const wdt = $("main").width();
$(".container").width(900);
$(".img-large").height(500);
$(".btn").innerWidth(200);    // with padding
$(".btn").innerHeight(50);
$(".btn").outerWidth(210);    // with padding and border
$(".btn").outerHeight(55);

// Add content
$("#my-div").append("Lorem ipsum")
$("#ul").prepend("<li>First</li>")
$("my-div").before(newDiv)
$("my-div").after(newDiv, newList)

// Move, copy, and remove
$("#img-author").appendTo("#author-intro");
$("#submit").clone().appendTo("#form2")
$(".img-small").remove();
$(".container").empty()       // remove all children

// Show, hide, toggle visibility
$("#sub-menu").show()
$("#sub-menu").hide()
$("#sub-menu").toggle()
// optional: add animation time in milliseconds .show(ms)
// optional: 2nd parameter callback to execute after

// Other animations
$("#sub-menu").fadeIn()
$("#sub-menu").fadeOut()
$("#sub-menu").fadeToggle()
$("#sub-menu").fadeTo(ms, opacity)
$("#sub-menu").slideUp()
$("#sub-menu").slideDown()
$("#sub-menu").slideToggle()
$("#my-div").animate({
  width: "900px",
  height: "500px"
}, 1000)
$("#my-div").animate({
  width: "+=50px",
  height: "+=50px"
}, 1000)
```

Ha több animációs parancsot írunk, ezeket a jQuery egymás után fogja végrehajtani.

## Events

```{js}
// $(selector).event(function)
// $(selector).on(event, function)

// Mouse events
$(".btn").click()  // $(".btn").on("click", function() {})
$(".btn").dblclick()
$("#my-img").mouseenter()
$("#my-img").mouseleave()
$("#my-img").mouseover()

// Keyboard events
$(document).keydown()
$(document).keyup()

// Form events
$(".btn").submit()
$(".input").change()
$(".input").focus()
$(".input").blur()

// Document events
$(document).ready()
$(document).resize()
$(document).scroll()

// Remove event handler
$(".btn").off("click")
```

Az event handler függvény hozzáférést kaphat az event objektumhoz, amely több hasznos tulajdonsággal és metódussal rendelkezik (pl. event.target). A `this` akárcsak sima JS-ben, itt is arra az elemre mutat, amelyhez az event handler kapcsolódik. Kiválasztása: `$(this)`.

Az adott eventet élesíthetjük a programmal is:

```{js}
$(".btn").trigger("click");
```