---
title: "JavaScript Development a gyakorlatban"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## ECMAScript modulok

A kezdetekkor a JavaScript csak rövid, interaktivitást biztosító kódrészleteket jelentett, de később, ahogy a nyelv fejlődött, és az alkalmazások mérete jelentősen nőtt, fontossá vált a programkód különálló file-okba való bontásának lehetősége, amelyet a modulok tesznek lehetővé.  
A modulok egyszerűen file-ok, amelyek olyan többé-kevésbé önálló kódot tartalmaznak, amelyet adott esetben több különböző helyzetben is fel szereténk használni. De sokszor csak annyi a cél, hogy a komplex alkalmazást könnyebben átlátható és kezelhető részekre bontsuk. A modulok lényege, hogy a más programok részére rendelkezésre bocsátani kívánt részeket exportáljuk, majd ezeket a másik scriptbe importálva használjuk. 

A modulok neveit camelCase-szel szokás írni, és `.js` kiterjesztésű file-okról van szó. Lehetséges `.mjs` kiterjesztést is használni, de ezt nem minden böngésző támogatja. 

A script file-t a html-be a szokásos `<script>` tagben csatolhatjuk, de jelezni kell, hogy modulról van szó. Ebben az esetben a `defer` kulcsszóra már nincs szükség, mert a böngészők automatikusan késleltetik a futtatást. Modul file-ok automatikusan strict módban futnak. Először az importált modulok kódja fut le.

```{}
<script type="module" ... >
```

A modulon belül deklarált változók module scope-úak. Azokat a változókat, függvényeket, osztályokat, amelyeket más scriptekben használni akarunk, exportálni kell.

A JS hivatalos modul rendszere az ES module rendszer. 

### Export és import

A modulokból exportálhatók változók, függvények (bármilyen formában deklarálva), osztályok egyaránt, de az export csak a kód legfelső szintjén történhet, függvényen belül pl. nem.

Az export lehet nevesített és default.
A nevesített export történhet egyszerűen az `export` kulcsszónak a deklaráció elé írásával, vagy a script végén az exportálandó változók nevesítésével. Lehetséges az exportált objektumok átnevezése.

```{js}
export const funName = () => {}
export class Person() {}

// vagy

export { funName, varName as newVarName, className };
```

A nevesítetten exportált objektumok importja is a név használatával történik, jellemzően a script elején. Relatív útvonalakat használunk. Lehetséges az importált objektumok átnevezése is.

```{js}
import { funName, newVarName, className as newClassName } from './moduleName.js';
```

Ha mindent importálni szeretnénk, akkor megadunk egy `namespace` objektumnevet, amely property-jeiként és metódusaiként férünk majd hozzá az importált objektumokhoz. Ez a fajta import megoldja az esetleges névütközéseket is, amelyeket körülményes lenne átnevezéssel megoldani. Ez a változat hasonlít pl. a Python modul-importjaira.

```{js}
import * as NamespaceName from './moduleName.js';
```

Default exportként modulonként egy objektumot tudunk exportálni. Ez esetben az `export default` kulcsszavakat írjuk eléje. Ezek lehetnek anonim objektumok is. 

Az importálás során az objektum a megadott nevet kapja majd, amelynek nem kell egyeznie az importált modulban szereplő névvel, sőt, az exportált objektum lehet anonim is.

```{js}
export default exportName;
```

```{js}
import anyName from './moduleName.js';
```

Egy modulban kombinálható a nevesített és az alapértelmezett export. Ilyenkor az import a következőképpen néz ki:

```{js}
import React, { useState, useEffect } from 'react';
```

Az importálás élő kapcsolatot jelent a forrással, vagyis, ha a modulban megváltozik az importált objektum, akkor abban a file-ban is megváltozik, amely importálja. Ez azért van, mert ugyanarra a memóriahelyre hivatkoznak. 

### Aggregátor file

Néhány esetbe ésszerű lehet a sok modul exportot egy aggregátor file-on keresztül továbbexportálni, és a fő js file-ba csak ebből az egyből importálni, ami egyszerűsíti a kódot.

Ilyen esetben használhatunk egy rövidített formát a továbbexportálásra, de a default importokkal vigyázni kell:

```{js}
export { add, subtract, multiply, divide } from './math.js';
export { name, age, profession } from './person.js';
export { default as aboutMe } from './bio.js';
```

### Más modul-rendszerek

Amikor a JS-t létrehozták, még nem volt modul-rendszere, ezért a fejlesztők saját modulrendszert írtak a JS alapjain. Ilyen például a CommonJS rendszer, amelyet pl. a node.js is használ.

## JavaScript projektek

### Node.js és npm

A Node.js egy JavaScript runtime, amely lehetővé teszi, hogy JavaScriptet futtassunk a böngészőn kívül, pl. szerveren. Kibővíti a JS funkcióit (pl. file-okhoz való hozzáféréssel), de természetesen nélkülözi azokat a funkciókat, amelyek például a böngészőhöz és a html dokumentumokhoz való hozzáférést tették lehetővé.

A Node.js egyik alkotórésze az npm, vagyis *node package manager*, amellyel hozzáférhetünk, és telepíthetjük a különböző JavaScript csomagokat. 

A projekt könyvtárban először az `npm init` parancsot futtatva a parancssorban, létrehozhatjuk a szüséges struktúrát, beleértve egy .json file-t, amely a projekt legfontosabb adatait tartalmazza, beleértve a szükséges csomagokat, illetve a node_modules mappát, amely a telepített csomagok programkódjait. 

A .json file lehetővé teszi, hogy a projektet a node_modules mappa nélkül másoljuk. Ez alapján bármikor telepíthetők a szükséges csomagok az `npm install` paranccsal. 

Új csomagokat az `npm install <package-name>` paranccsal, a fejlesztéshez szükséges csomagokat pedig a `npm install <package-name> --save-dev` paranccsal adhatunk hozzá. Utóbbiak közé tartozik például a bundler, amelyet ahhoz használunk, hogy a forráskódokból feltölthető file-okat hozzon létre. Pl. Parcel, Webpack.

### Development server

A bundlerek része általában valamilyen web server, amely lehetővé teszi, hogy a változtatások hatását rögtön láthassuk.
Parcel esetében ezt az `npx parcel <entry-point>` paranccsal tudjuk elindítani, ahol az entry point az a html file, amelybe a fő script file-t csatoltuk. 

A másik mód a package.json-ban scriptek írása: pl. `"start": "parcel index.html"`, amely után az egész futtatható az `npm run start` paranccsal. 

### ES6 &rarr; ES5 transzpiláció és polyfill

A kompatibilitás érdekében bizonyos modern JS funkciókat olyan formában kell átírni, hogy a régebbi böngészők is futtatni tudják. Ezt nem kell manuálisan megtenni, hanem a Babel nevű program használható, amelyet pl. a Parcel is használ. Ezen kívül a polyfill-hez szükséges a `core-js` és a `regenerator-runtime` csomag, amelyek lehetővé teszik az új funkciók használatát. 

Ezeket telepíteni kell a projekthez az npm segítségével (NEM devDependency-ként), majd importálni a .js file-okba. 

### Build

Ahhoz, hogy az alkalmazásunkat mások használni tudják, olyan formába kell önteni, amit a böngészők kezelni tudnak. Ehhez module bundlereket kell használni, amelyek a modul file-okat egyetlen futtatható JS file-ba csomagolják.

Ilyen bundler a parcel és a webpack is. Ezeket npm-mel dev-dependency-ként telepítünk.

A file-okat a src könyvtárban hozzuk létre és alapértelmezetten a dist könyvtárban hozzák létre a csomagolt file-okat.

Hasonlóan a development server scriptjéhez, a végső build script is megírható: `"build": "parcel build index.html"`, és ezután `npm run build`, amely végrehajtja a végső csomagolást, és létrehozza a megosztható file-okat. Az alkalmazás/weboldal ezek után feltölthető a kiválasztott hosting platformra.

További információ a module bundlerek (webpack) használatáról [itt található](https://www.freecodecamp.org/news/javascript-es-modules-and-module-bundlers/)

## Clean code és programozási paradigmák

Ahhoz, hogy a programkód mások, illetve némi idő elteltével magunk számára olvasható, követhető legyen, illetve jól bővíthető, fejleszthető maradjon, érdemes tartani magunkat az alábbi szempontokhoz:  

1. Olvasható kód: ne legyen túlkomplikált, beszédes változóneveket és függvényneveket használjunk, a változónevek arról szóljanak "mi van benne", a függvénynevek arról "mit csinál"
2. Általános szempontok: 
  - Don't Repeat Yourself (DRY): függvények használata az ismétlődő kódra 
  - Don't pollute global namespace: encapsulation használata
  - Szigorúbb ekvivalencia ellenőrzése: `=== > ==`
3. Függvények:
  - Minden függvény egy dolgot csináljon, jól
  - Ha lehetséges, max. 3 paramétert használjon
  - Ha lehetséges, adjunk meg default paramétereket
  - A return érték legyen ugyanolyan típusú, mint az input
  - Az arrow függvények olvashatóbbá teszik a kódot
4. OOP:
  - ES6 classok használata
  - Data encapsulation: a class-ok adatait kívülről ne változtassuk, használjunk public API-t ezek módosítására
  - Method chaining használata: a `return this` révén
5. Többszörösen beágyazott kód nehezen olvasható
  - Guard clauses: `if (condition) return;`
  - Ternary expression > if-statement
  - Több if > if-else 
  - For loop kerülése: forEach, map, stb.
6. Async kód:
  - async/await > then
  - parallel promise handling
  - hibák és elutasított ígéretek explicit kezelése
  
## Imperatív és deklaratív kód, funkcionális programozás

Imperatív kód: megadjuk a lépéseket, amelyeket végre kell hajtani (pl. for loop)
Deklaratív kód: leírjuk, hogy milyen eredményt szeretnénk, de a hogyant a programra bízzuk, hogy elvégezze a háttérben (pl. map, filter)

A deklaratív programozás példái: destrukturálás, spread operátor, ternary operátor, template literal

Funkcionális programozás: A deklaratív kód alparadigmája

Alapelvei:  

1. Tiszta, mellékhatás nélküli függvények kombinálása: nem függnek és nem módosítanak a függvény scope-ján kívüli változókat.
2. Immutabilitás: nem módosítanak a state adatokon, mindig másolatokat használnak

## Model-View-Controller (MVC) architecture

Az MVC népszerű módja a projektek felépítésének. Lényege a vonatkozások szétválasztása, vagyis a különböző feladatokat a program különböző moduljai látják el. Három részből áll a projektstruktúra:  

1. A model tartalmazza az alkalmazás adatait, állapotát (state) és felelős a különböző számításokért, a http requestekért (pl. API, adatbázis elérése). A modelben gyakran kezelünk egy state objektumot, amelyet az egyes függvények módosítanak. Ezek egy részét exportáljuk, hogy a controller hozzáférjen, és hívni tudja, pl. bizonyos eventek esetén.
2. A view felel az eredmények megjelenítéséért, a grafikus felhasználói felületért. 
3. E kettő között nincs közvetlen kapcsolat (pl. nem importálják egymás exportjait), hanem a a controller köti össze ezeket, amely a modellel kommunikálva hívja az ottani függvényeket az adatok módosításához, majd ezeket továbbítja a view-nek, hogy az megjelenítse. 

A három nagy részen belül természetesen lehetnek külön modulok, amelyek egy-egy komponensért felelnek, így pl. külön view-k és külön controllerek a különböző jellegű feladatokra. 

### Eventek az MVC-ben: a Publisher-Subscriber modell

Ahhoz, hogy a controllerben hozzáférjünk a view adataihoz, illetve Event listenereket regisztrálhassunk, amelyek a controller révén hívják a model függvényeit, a publisher-subscriber mintát használhatjuk: a controllerben a view bizonyos metódusát (pl. addHandler) egy függvény paraméterrel hívjuk, amely a handler függvény lesz, amelyet bizonyos event callback-jeként regisztrálunk a view-ben.