---
title: "JavaScript Adatstruktúrák"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## Array

A legalapvetőbb adatstruktúra, amely tulajdonképpen megfelel a Python Listjeinek. 

Deklarálása `[]` zárójelekkel vagy a `new Array()` paranccsal történik:
```{js}
const friends = ["Thomas", "Peter", "Kate"]

const family = new Array("Susan", "James", "Jane")
```

Akárcsak a Pythonban, az `Array` elemei vegyes típusúak is lehetnek, akár változók, számítások, függvényhívások is:
```{js}
const newArray = ["Andris", 1986, ["Andrea", "Andris", "Matyi", "Marci"], true, calcAge(1986)]
```

Ugyanakkor, ellentétben az R-rel, és ugyancsak hasonlóan a Pythonhoz, az array-ek nem vektorizáltak, vagyis ha minden elemen végre szeretnénk hajtani valamilyen műveletet, akkor ciklust kell használni.

### Műveletek

Az `Array` elemeihez az index-számuk segítségével férhetünk hozzá. Akárcsak Pythonban, az indexek 0-val kezdődnek. Ugyanígy új értéket rendelhetünk az egyes pozíciókhoz, még akkor is, ha az array-t a `const` paranccsal hoztuk létre, csak az egész array-t nem cserélhetjük másikra / más adattípusra.

```{js}
console.log(friends[0])   // "Thomas"
console.log(friends[2])   // "Kate"
friends[1] = "Robert"

friends = ["Jack", "Jim", "Sarah"]    // Error
```

Az `Array` objektumtípushoz számos metódus tartozik. Néhány fontosabb:

```{js}
friends.length              // Elemek száma
friends.push("Robert")      // Elem hozzáadása a végére - return: elemek száma
friends.pop()               // Utolsó elem törlése - return: utolsó elem
friends.shift("Dave")       // Elem hozzáadása az elejére
friends.unshift()           // Törlés az elejéről
friends.concat(newFriends)  // Két array összefűzése
friends.indexOf("Thomas")   // Elem sorszáma - első előfordulás - return: sorszám
friends.includes("Kate")    // Tartalmazza-e az adott elemet - return: true/false
```

Egyes metódusok kiválthatók a haladóbbakkal, illetve a ...spread operátorral.

#### in  

Array-ek esetében az `in` haszálható az indexek iterálására (`for ... in ...`), de arra is, hogy megnézzük, az adott indexen található-e érték

```{js}
console.log(5 in friends)
```

#### Array.at()

Az ES2022 bevezette az `.at()` metódust, amely egyrészt kiválthatja a hagyományos hozzáférést az elemekhez, de ezen kívül az előnye, hogy negatív indexekkel is használható.

```{js}
// Utolsó elem
console.log(friends[friends.length -1]);
console.log(friends.slice(-1)[0]);

console.log(friends.at(-1));
```

Ez a metódus stringekkel is működik.

```{js}
let name = "Peter"
console.log(name.at(0))   // "P"
console.log(name.at(-1))  // "r"
```

### Destrukturálás

Az `Array` elemei változókba menthetők. Lehetőség van az összes elem kimentésére, de ki is hagyhatók elemek. Ez lehetővé teszi azt is, hogy két változó értékét megcseréljük. Miután egyes elemeket kimentettünk változókba, van rá lehetőség, hogy a fennmaradó elemeket is változóba mentsük (`rest pattern`)

```{js}
const [x, y, z] = arrName;  // Az első három elemet kapja az x, y, és z változó
const [x, , y] = arrName;   // Az első és a harmadik elemet mentjük változóba

// Nested destructuring
const nestedArr = [2, 4, [5, 6]]
const [i, , [j, k]] = nestedArr   // i = 2, j = 5, k = 6

// Default values
const shortArr = [1, 2]
const [a, b, c] = shortArr              // a = 1, b = 2, c = undefined
const [a = 0, b = 0, c = 0] = shortArr  // a = 1, b = 2, c = 0 (default)

// Switch
[main, secondary] = [secondary, main]

// In function definition
const profile = ["Oluwatobi", "Sofela"];

function getUserBio([firstName, lastName]) {
  return `My name is ${firstName} ${lastName}.`;
}

// Rest pattern
const [a, b, ...others] = [1, 2, 3, 4, 5]   // a = 1, b = 2, others = [3, 4, 5]
```

Objektumok is destrukturálhatók (ld. ott).

### Spread operátor

Minden iterálható adattípuson működik, elemeket array-be rendezi. Használható array másolására, illetve két vagy több array egyesítésére is, illetve arra, hogy több függvény paramétert megadjunk. Az ES6 objektum property megadásban bevezetett könnyítései révén így objektumokat is beilleszthetünk másik objektumba, és másolhatjuk az objektumot.

```{js}
const newArr = [1, 2, ...arr]
const arrCopy = [...oldArr]
const menu = [...starterMenu, ...mainMenu]
const letters = [...string]

console.log(...arr)
restaurant.orderPasta(...ingredients)

newRestaurant = {
  founded: 1998, 
  founder: 'Giuseppe',
  ...restaurant
}

restCopy = {...restaurant}
```

## Object

A JavaScript objektumai hasonlítanak a Python dictionary adatstruktúrához, azzal a különbséggel, hogy a kulcsok (itt: `property`) csak `string` típusúak lehetnek, és nem ismétlődhetnek. Ha ismétlődnek a property nevek, akkor a későbbi felülírja a korábbi értéket. 
Az egyes `property` értékek viszont bármilyen `expression` típusú értékek lehetnek, beleértve a függvényeket (ezek az objektum metódusait hozzák létre)

Deklarálás:
```{js}
const andras = {
  firstName: "András",
  surname: "Morauszki",
  birthYear: 1986
  age: calcAge(this.birthYear)
  greet: function() console.log(`Hello, ${this.firstNames}`)
}
```

Az objektum elemei tetszőleges sorrendben következhetnek. Indexekkel nem hozzáférhetők. A hozzáférésnek két módja van. A `bracket notation` használható, ha a `property` nevet is programatikusan kapjuk.

Új property is e két módon hozható létre. A törlés pedig a `delete` paranccsal történik. Az előhívott property elemeken minden, az adott elemtípusnak megfelelő metódus használható (pl. length)

```{js}
// dot notation
console.log(andras.firstName)

// bracket notation
console.log(andras['birthYear'])

andras.family = ['Andrea', 'Andris', 'Matyi', 'Marci']
andras['profession'] = "researcher"

console.log(andras.family.length)
console.log(andras.family[0])
```

Új objektum létrehozásánál az ES6 óta felhasználhatunk változókat. Ebben az esetben az alábbi rövidített forma is működik. Az objektumnak ezután lesz egy height property-je, amely 180 értéket vesz fel, weight property-je, amely 80, és gender property-je, amely a "male" értéket veszi fel.

```{js}
const height = 180
const weight = 80
const gender = "male"

const johnDoe = {
  height,
  weight,
  gender
}
```

Az ES6 óta a property nevek lehetnek számítottak is, vagy nyerhetjük azokat változókból. Ebben az esetben a property nevet, bármilyen kifejezést [] közé kell írni.

```{js}
const id = 1234
const email = john@doe.com
const user = {
  [`user_${id}`]: `${email}`
}
```

### Objektum metódusok

Az objektum eleme lehet függvény is, amely új metódust hoz létre az objektumhoz. Ezen belül gyakran használják a `this` kulcsszót, amely ebben az esetben magát az objektumot jelöli, és egyrészt megfelel a DRY kritériumnak, másrészt jól másolhatóvá teszi a metódust (`object borrowing`).

```{js}
const andris = {
  birthYear: 2015,
  calcAge: function() {
    this.age = 2021 - this.birthYear;
    return this.age
  }
}
```

Objektum metódusként nem jó arrow functiont használni, mert ebben az esetben a `this` nem az objektumra utal, hanem az azt magába foglaló kontextusból veszi, de metóduson belül jól használható, mert ebben az esetben a magába foglaló függvénytől veszi, tehát az objektumra utal.

Az ES6 óta ezeket a metódusokat rövidített formában (a `function` parancs nélkül) is hozzáadhatjuk az objektumhoz. Az argumentumok közvetlenül a metódusnév után jönnek, majd kapcsol zárójelek közé kerül a metódus teste:

```{js}
objName = {
  funName (args) {},
}
```

### Hasznos objektum metódusok

```{js}
// Csak saját property (öröklött nem)
andras.hasOwnProperty('friends')

// Öröklött is
console.log('friends' in andras);

// Merge, copy, add, overwrite

// andras-t is felülírja!
let newAndras = Object.assign(andras, user)

// Többet is lehet, és üres objektumhoz is
let newAndras = Object.assign({}, andras, user)
let newPerson = Object.assign({}, person, {name: 'Bob'})
// Így (is) másolhatunk objektumot
let objectCopy = Object.assign({}, oldObject)
```

### Objektumok destrukturálása

Az `Array`-ekhez hasonlóan destrukturálhatók az objektumok is. Ebben az esetben nem a sorrend, hanem a változó és az objektum `property` névazonossága számít. Az így destrukturált `property`-knek új neveket adhatunk. Mindez nem csak új változók létrehozásánál működik, hanem mutálásuknál is. Az objektum destrukturálás jól használható function callokban, hiszen így nem számít a sorrend, amelyben megadjuk az objektumokat.

```{js}
const { firstName, surname, birthYear } = andras
// De:
let firstName, surname
({ firsName, surname } = andras);

// Rename ( property: varName )
const { firstName: givenName, surname: familyName, birthYear: year } = andras

// Default value
const { firstName = "", surname = "", birtYear, age = 0, friends = []} = andras

// Nested
const { family: {wife, firstChild, secondChild} } = peter

// Rest
const { sat, ...weekdays } = restaurant.openingHours

// Function call
const funName = function({ arg1, arg2 }) {}
funName(objArg)
```

### Optional chaining

Főleg többszintű objektumoknál lehet hasznos, ha mélyen lévő adatot próbálunk előhívni. Ha valamelyik property vagy array elem, vagy bármi nem létezik, akkor nem ad hibát, hanem `undefined` értékkel rövidre zárja a parancs futását. Ez is a `nullish` értékeket figyeli, vagyis `null` és `undefined` esetén jelez.

```{js}
obj.prop1?.prop2
obj.method?.(args)
arr[i]?.prop
```

## Set

A `set` (halmaz) egyedi elemek gyűjteménye. `Array`-ből hozhatjuk létre a `new Set` függvény segítségével. Ennek sem kell homogénnek lennie. Iterálható, de a sorrend irreleváns. Ezért nem lehet hozzáférni az egyes elemekehez, csak megnézni, egy adott érték eleme-e, illetve iterálható a `for... of` ciklus segítségével.
Létrehozhtató array mellett stringből is. Visszaalakítható array-é a `...` spread operátorral.

```{js}
const numbers = new Set([1, 3, 5, 3, 2, 1, 5, 7, 2])
const letters = new Set("abracadabra")
const meals = new Set(["Pizza", "Pasta", "Soup", "Pasta"])

const arr = [...setName]
```

### Set property-k és metódusok

A metódusok már a létrehozásakor hozzáadhatók.

```{js}
numbers.size
meals.has("Pizza")
meals.add("Tiramisu")
letters.delete("c")
numbers.clear()

const letterNumber = new Set("abracadabra").size
```

## Map

Az `Object`-hez hasonló adatstruktúra, de a `key` bármilyen típusú érték lehet, akár boolean, objektum vagy függvény is.
Iterálható a `for... of` segítségével.

Létrehozása többféleképpen történhet:

```{js}
const restaurant = new Map();
restaurant.set("name", "Classico Italiano");
restaurant.set(1, "Firenze, Italy").set(2, "Lisbon, Portugal")
  .set(true, "The restaurant is open").set(false, "We are closed")
  
const question = new Map([
  ["question", "Which is the best programming language?"],
  [1, "C"],
  [2, "Java"],
  [3, "JavaScript"],
  [4, "Python"],
  ["correct", 3],
  [true, "Correct!"],
  [false, "Wrong! Try again!"]
])

const newMap = new Map(objName.entries())
```

### Map property-k és metódusok

```{js}
restaurant.get("name")
restaurant.get(time > restaurant.get("open") && time < restaurant.get("closed"))

restaurant.has(key)
restaurant.delete(key)
restaurant.size
restaurant.clear()

// Iterators
restaurant.entries()    // Key-value pairs
restaurant.keys()
restaurant.values()

// Konvertálás
const arrayOfKeys = [...restaurant.keys()]
const arrOfValues = [...restaurant.values()]
```

## Összehasonlítás

Array vs. Set: ha manipulálni akarjuk, illetve egyes elemekhez hozzáférni, array-t érdemes használni. 
Object vs. Map: előbbit egyszerűbb létrehozni, és könnyebb hozzáférni az elemekhez, illetve metódusokat tudunk hozzá írni. A Map előnye, hogy másféle key értékeket is elfogad, illetve hogy jobb teljesítményt nyújt, és könnyű iterálni.