---
title: "DOM manipuláció"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## Elemekhez való hozzáférés

```{js}
let doc = document.documentElement    // root
let head = document.head
let body = document.body

// Ha csak egy van, vagy csak az első kell
let navigation = document.querySelector("nav")
let button = document.querySelector(".btn")
let image1 = document.querySelector("#img1")

// vagy (nem kell #)
let image2 = document.getElementById("img2")

// ha több van
let paragraphs = document.querySelectorAll("p")
let images = document.getElementsByTagName("img")
let tagList = document.querySelectorAll(".tag")
let tagList2 = document.getElementsByClassName("tag")
```

### querySelectorAll vs. getElementsBy...

A `querySelectorAll` komplexebb `CSS selectorokat` is elfogad, és egy `Nodelist`-et ad, míg a `getElementsBy...` függvények csak egyszerű nevekkel működnek, és `HTMLCollections`-t ad vissza, amelyen pl. nem működik a `forEach`. Ezt a `...` operátorral ki lehet kerülni.

A másik különbség, hogy a `querySelector` függvények magát az elemet másolják, míg a `getElementBy` függvények csak referencia típusú változót (`live collection`) hoznak létre, vagyis, ha a DOM megváltozik, ezek értékei is megváltoznak (pl. elemek programatikus törlése).

```{js}
let image = document.querySelector("#intro img")
let activeBtns = document.querySelectorAll(".btn.active")

// Looping
document.querySelectorAll(".btn").forEach(button => button.addEventListener("click", () => {}))
[...document.getElementsByClassName("btn")].forEach(button => {})
```

### Kapcsolódó elemekhez való hozzáférés

```{js}
element.childNodes        // összes child node
element.children          // összes child element
element.firstChild        // csak az első child node
element.firstElementChild // csak az első child element
element.lastChild         // csak az utolsó child node
element.lastElementChild  // csak az utolsó child element
element.hasChildNodes     // true vagy false
element.nextSibling       // következő ugyanazon a szinten (csak közvetlen szomszéd)
element.nextElementSibling  // következő element
element.previousSibling   // előző ugyanazon a szinten
element.previousElementSibling // előző, de csak element
element.parentNode        // parent node (közvetlen)
element.parentElement     // parent element (közvetlen)
element.parentElement.children  // a közvetlen szülő összes közvetlen gyermeke
element.closest('div')    // legközelebbi a selectornak megfelelő (közvetett is) felfelé
element.querySelectorAll("a")  // lefelé: összes link az element leszármazottai között
```

## Elemek tartalmához, stílusához és attribútumaihoz való hozzáférés

A kiválasztott elemek tartalmáhz hozzá lehet férni pl. az `innerHTML` vagy `textContent`, input elemek esetén a `value` metódusokkal, a CSS stílushoz pedig a `style` metódussal, amely segítségével minden CSS property módosítható. A kötőjeles `property`-k neveit ebben az esetben camelCase-ben kell írni.

A html elemek attribútumai közül a standard attribútumok (pl. img esetében src, a esetében href, stb.) hozzáférhetők. A nem standard attribútumok a `getAttribute()` függvénnyel férhetők hozzá.

```{js}
// Tartalom
let text = document.querySelector("p").textContent;  // Csak szöveg
let content = document.querySelector("#intro").innerHTML   // szöveg a tagekkel együtt
let age = document.querySelector("#age").value;

// Stílus
let color = document.querySelector("h1").style.color;     // inline style-ok
let fontSize = getComputedStyle(message).height           // computed CSS style-ok

// Attribútumok
console.log(image.src)                    // Absolute path
console.log(image.getAttribute("src"))    // Relative path

console.log(link.href)                    // Abszolút
console.log(link.getAttribute("href"))    // Relatív

let designer = document.querySelector("#logo").getAttribute("designer")   // non-standard attribute

// Data attribútumok
// <article id="electric-cars" data-index-number: "12314">...
const article = document.getElementById("electric-cars")
console.log(article.dataset.indexNumber)

// Módosítás
document.querySelectorAll("h1").style.fontSize = "18px";
document.querySelectorAll("h1").style.textTransform = "uppercase"
document.querySelector("textarea").value = "";
link.href = "http://www.google.com"
logo.setAttribute('company', 'Bankist')

// Class-ok módosítása
section.classList.contains("active")
section.classList.add("active")
section.classList.remove("active")
section.classList.toggle("active")
```

## Elemek létrehozása, hozzáadása és törlése

```{js}
insertAdjacentHTML

// Programatikus létrehozás - live element
const newEl = document.createElement(tagName)
const newText = document.createTextNode(string)
newEl.classList.add("class-name")
newEl.appendChild(newText)

// Klónozás
element.cloneNode(true)   // incl. child elements 

// Insert and move
// Insert if new
// Move if already present
parent.prepend(child)   // first child
parent.append(child)    // last child
parent.appendChild(child)  // last child
parent.insertBefore(div1, div2)  // as child before div2
element.before(message)    // sibling
element.after(message)     // sibling

// Törlés és csere
element.remove()      // Preferred
parent.removeChild(child) // Supported by older browsers
parent.replaceChild(newNode, oldNode)
```

## Eventek hozzáadása és törlése

Az egyes DOM elemekhez Event listenereket adhatunk, amelyek bizonyos események bekövetkeztekor függvényeket futtatnak, így lehetővé téve a felhasználó interakcióját a weboldallal. Ilyenekből egy elemhez több is megadható (pl. klikk, billentyű lenyomása, stb.), és ezek programatikusan törölhetők, ha a függvény nevesített.

```{js}
button.addEventListener("click", function() {
  this.classList.toggle("active")
})
document.addEventListener("keydown", (e) => {
  if (e.key === "Enter") {
  
  }
})

element.removeEventListener("click", funName)
```

Az `event listeneren` belül a `this` a DOM objektumra utal.
Az `e.target` pedig arra az elemre vonatkozik, ahol az adott esemény (pl. kattintás) megtörtént.
Az `e.currentTarget` az az elem, ahová a handlert csatoltuk (=== this)

### Fontosabb eventek  

**click/dblclick/contextmenu:**  
Elementekhez kapcsolhatók és kattintással élesednek.  
Az event objektumon van egy button property, amellyel megállapítható, melyik gombbal történt a klikkelés, illetve olyan property-k, mint a `shiftKey`, `altKey`, `ctrlKey`, amelyek boolean értékkel jelzik, mely további billentyűk voltak lenyomva  klikkelés közben.  
A kattintás helyének kezeléséhez a window-hoz viszonyított `clientX`/`clientY` és a dokumentumhoz viszonyított `pageX`/`pageY` property-k használhatók.

*Double click-nél mellékhatás a szöveg kijelölése. Ez megakadályozható, ha az elementhez `mousedown` eventet csatolunk, amelyben a `return false`-szal semlegesítjük ezt a viselkedést.*

*Az oldal másolását meggátolhatjuk az `oncopy` event használatával, amelyben ugyancsak a return false-szal meggátolhatjuk, és opcionálisan felugró ablakkal figyelmeztethetjük a felhasználót.* 

**mouseenter/mouseleave vagy mouseover/mouseout, mousemove:** 
Az elementekhez kapcsolhatók, és az egér mozgása tudja elindítani ezeket. Az első két pár abban különbözik, hogy az eventet csak az indítja el, ha maga az elem fölé húzzuk az egeret, vagy a gyermekek is. A `mousemove` minden, az elem fölötti egérmozgásra élesedik.

**drag&drop eventek:**

**scroll eventek:**

Az elemek pozíciója az elemhez kapcsolódó `.getBoundingClientRect()` metódussal kapható meg. Az adott scroll pozíció a `window` objektum `scrollY` property-jével férhető hozzá.
A `scroll` event a legkisebb görgetésnél is élesedik, ami nem túl gazdaságos megoldás. Jobb alternatíva az Intersecion Observer API használata.

**keyboard eventek:**

**form és input eventek:**

**életciklus eventek:**
Vannak olyan esetek, amikor egy-egy függvényt akkor akarunk futtatni, amikor a DOM/oldal betöltött, vagy épp azelőtt, hogy valahonnan kilépünk.

`DOMContentLoaded`: akkor élesedik, amikor a html és js file-ok betöltenek, de ebbe nem tartoznak bele bl. a képek. A documenten hozható létre
'load': akkor élesedik, amikor minden betöltött, a window-on hozható létre
'beforeunload': akkor élesedik, mielőtt bezárul az ablak, szintén a window-on hozható létre. Néhány böngészőben a preventDefault metódust is használni kell ebben az esetben. 

**További információ**  
Az eventek típusáról összefoglaló és további információk [itt](https://developer.mozilla.org/en-US/docs/Web/Events) találhatók.

### Eventek sorrendje: bubbling és capturing

`bubbling`:  Belülről kifelé
`capturing`: Kívülről befelé

```{js}
element.addEventListener("click", myFunc, useCapture)

// Bubbling
element.addEventListener("click", myFunc, false)
// Capturing
element.addEventListener("click", myFunc, true)
```

Az alapértelmezett sorrend a bubbling: először a belül lévő elemeken élesednek a függvények (ha ua. az Event listener több szinten is hozzá van adva). Ez a delegáció miatt hasznos tulajdonság.

A **delegáció** lényege, hogy komplexebb elemeknél a szülő kapja az event listenert, és így nem csak az adott elemre (pl. span-re) való kattintás, hanem a teljes befoglaló elemre (pl. div-re, gombra) való kattintás is élesíti a függvényt.

A propagáció le is állítható az `event.stopPropagation()` metódussal, de ez általában nem jó ötlet, csak komplex alkalmazásokban lehet rá szükség.

Nem minden event esetében használható a propagáció. Ebben különböznek pl. a `mouseenter`/`mouseleave` és a `mouseover`/`mouseout` eventpárok. Utóbbiak akkor is élesednek, ha az adott elem valamelyik gyermeke fölé megyünk egérrel (vagy húzzuk el az egeret), míg előbbiek nem. 

Az `addEventListener` kaphat egy opciók objektumot is harmadik paraméterként, amelyen szintén megadhatjuk a `capture: true` értéket, hogy "lefelé" élesedjenek az események (alapértelmezett értéke false).

Ebben szintén megadhatjuk, hogy egy esemény csak egyszer élesedhessen (`once: true`), ami hasznos lehet pl. checkout gomboknál, amelyeknél nem szeretnénk, hogy valaki véletlenül többször rákattintson. Ez az opció az event élesedése után automatikusan eltávolítja a listenert.

### Argumentumok hozzáadása

Alapesetben az event handlerek egy függvény hivatkozást várnak. Ebben azonban nem tudunk paramétereket megadni a függvényhez. További argumentumokat nem fogadnak el: az első argumentum az event, a második a callback függvény. Ez utóbbi mindig hozzáférhet az event objektumhoz, amelyet paraméterként megkap, de ha másik paramétert is meg kell adni, arra közvetlenül nincs lehetőség. 

Az első lehetőség anonim függvényeket definiálni az event handlerben, amely fő részében egy másik függvényt hívunk, a megadott paraméterekkel. 
A második lehetőség pedig a `.bind` metódus használata, amelyben a this-t bármilyen értékhez hozzáköthetjük, akár a szükséges paraméter érétkhez. Ha több paraméterre is szükségünk van, akkor a this-t egy array-hez vagy objektumhoz is köthetjük.

```{js}
// A megoldás (anonim függvény)
const handleHover = function (e, opacity) {
  if (e.target.classList.contains('nav__link')) {
    const link = e.target;
    const siblings = link.closest('.nav').querySelectorAll('.nav__link');
    const logo = link.closest('.nav').querySelector('img');

    siblings.forEach(el => {
      if (el !== link) el.style.opacity = opacity;
    });
    logo.style.opacity = opacity;
  }
};

nav.addEventListener('mouseover', function(e) {
  handleHover(e, 0.5);
});
nav.addEventListener('mouseout', function(e) {
  handleHover(e, 1);
})

// B megoldás (bind)
const handleHover = function (e) {
  if (e.target.classList.contains('nav__link')) {
    const link = e.target;
    const siblings = link.closest('.nav').querySelectorAll('.nav__link');
    const logo = link.closest('.nav').querySelector('img');

    siblings.forEach(el => {
      if (el !== link) el.style.opacity = this;
    });
    logo.style.opacity = this;
  }
};

nav.addEventListener('mouseover', handleHover.bind(0.5));
nav.addEventListener('mouseout', handleHover.bind(1));
```

## CSS stílus változtatása

```{js}
// Custom properties
document.documentElement.style.setProperty('--color-primary', 'orangered')
```

## Pozíció és scroll

```{js}
// Elemek
element.getBoundingClientRect()

// Scroll position
window.pageXOffset
window.pageYOffset

// Viewport height & width
document.documentElement.clientHeight
document.documentElement.clientWidth

// Scroll to
window.scrollTo({
  left: elementCoord.left + window.pageXOffset,
  top: elementCoord.top + window.pageYOffset,
  behavior: "smooth",
});

element.scrollIntoView({ behavior: "smooth" });
```

### IntesectionObserver

Használatához először egy új observert kell létrehozni. Ezután a létrehozott observer meg tudja figyelni a kívánt objektumot. Megadunk továbbá egy objektumot, amely a figyelés opcióit tartalmazza, és egy callback függvényt, amelyet végre fog hajtani.

Az opciókban megadunk egy root elementet, amellyel figyeljük a megadott element átfedését. Ha `null`-t adunk meg, akkor a viewportot figyeljük. A második opció, a threshold adja meg, mekkora átfedésnél élesedik a függvény. Ez lehet egyetlen érték vagy array is. Harmadik opcióként megadhatunk egy margin értéket (csak px-ben), amennyivel korábban/később élesedik a függvény (pl. a navigáció magasságával eltolhatjuk).

A callback függvény automatikusan hozzáfér egyrészt a megfigyelt elemhez (IntersectionObserverEntry), és magához az observerhez, ami révén például eltávolítható az observer az elemről, ha teljesül valamilyen feltétel, és már nincs rá szükség (pl. előtűnő szekciók, lazy loading után). A megfigyelt elemen megjelenik az isIntersecting tulajdonság, amelyet fel tudunk használni. A függvény mindig élesedik, ha valamelyik irányba átlépjük a küszöböt.

Az opciók és a függvény közvetlenül az új observer paramétereiként is megadható, de külön is létrehozható.

```{js}
// callback
const stickyNav = function (entries) {
  const [entry] = entries;

  if (!entry.isIntersecting) nav.classList.add('sticky');
  else nav.classList.remove('sticky');
};

const navHeight = nav.getBoundingClientRect().height;

// observer, opciók közvetlenül megadva
const headerObserver = new IntersectionObserver(stickyNav, {
  root: null,
  treshold: 0,
  rootMargin: `-${navHeight}px`,
});

// megfigyelés indítása
headerObserver.observe(header);

// Reveal sections
const revealSection = function (entries, observer) {
  const [entry] = entries;

  if (!entry.isIntersecting) return;

  entry.target.classList.remove('section--hidden');
  observer.unobserve(entry.target);
};

const sectionObserver = new IntersectionObserver(revealSection, {
  root: null,
  threshold: 0.15,
});
allSections.forEach(function (section) {
  sectionObserver.observe(section);
  section.classList.add('section--hidden');
});
```