---
title: "Java Script függvények"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```


## Függvények létrehozása

JavaScriptben többféle szintaxis áll rendelkezésre, hogy függvényeket definiáljunk.

### Function declaration

A `function` kulcsszóval történik, amely után a függvény neve, paraméterei, illetve maga a függvény teste, a végrehajtandó parancsok szerepelnek. A másik két móddal ellentétben az így megadott függvények már a létrehozásuk előtt hívhatók (a `hoisting` révén), így például kölcsönösen egymást hívó függvények írhatók.

```{js}
function functionName(parameters) { }
```

### Function expression

A függvényt változónévvel címkézzük fel, a szokásos `var/let/const` változódeklarálással. Ezek a függvények csak definiálás után hívhatók.

```{js}
const functionName = function(parameters) { }
```

### Arrow function

Ugyanúgy változóként hozzuk létre, de a szintaxis más, a használt `=>`-ból kapta a nevét. Ha csak egysoros a parancs, akkor automatikusan visszaadja az eredményt, nem kell a `return` kulcsszót használni. Többlépéses program esetében viszont használni kell. Ha csak egy paramétert használ, akkor nem kell zárójelezni, többnél viszont igen.

```{js}
const functionName = (parameters) => { }
const anotherFunction = parameter => { }
```

Az arrow functionben is jól használható a `this` kulcsszó, amely az arrow functiont magába foglaló függvény `this`-ét veszi át.

## Return kulcsszó

Akár a többi programnyelvben, a `return` kulcsszó teszi lehetővé, hogy a függvény valamilyen eredményt adjon. Egyébként a függvényen belül létrehozott változók csak a függvényen belül férhetők hozzá. A `return` parancs rögtön ki is lép a függvényből, a többi sort nem futtatja. Az arrow function esetében lehetséges az autoreturn, ha csak ez az egy parancs képezi a függvény testét.

```{js}
const calcAge = function(birthYear) {
  age = 2021 - birthYear;
  return age;
}

function calcAge2(birthYear) {
  age = 2021 - birthYear;
  return age;
}

const calcAgeArrow = birthYear => 2021 - birthYear;
```

## Függvény paraméterek/argumentumok

JavaScriptben is van lehetőség a függvényeket bizonyos paraméterek megadásával futtatni. Az így megadott argumentumok az értékükkel kerülnek be, vagyis nem magát az objektumra mutató hivatkozást kapja a függvény, hanem egy másolatot. 

### Rest parameters

Ha nem tudjuk előre, hány paramétert akarunk megadni, akkor használhatjuk a rest pattern megadást, amely a megadott paramétereket array-jé alakítja, és úgy továbbítja a függvénybe.

```{js}
const add = function(...numbers) {}
```

### Defalult parameters

Az ES6 változat óta van rá lehetőség, hogy bizonyos paraméterekhez alapértelmezett értéket adjunk meg. Ez lehet egy korábbi paraméter értéke is. Mivel a paraméterek csak sorban adhatók meg, ezért az alapértelmezett értékekkel ellátottaknak a végére kell jönniük. Arra viszont van lehetőség, hogy ezek közül valamelyik korábbi értékét ne adjuk meg.

```{js}
const createBooking = function(flightNum, numPassengers = 1, price = 199*numPassengers) {}

createBooking('LH123')    // 2. és 3. default
createBooking('LH123', 2) // 3. default
createBooking('LH123', undefined, 200)  // 2. default
```

## Objektum metódusok

Objektumok tulajdonságainak értéke függvény is lehet. Ezeket az adott objektum metódusainak nevezzük. Ezen belül gyakran használják a `this` kulcsszót, amely ebben az esetben magát az objektumot jelöli, és egyrészt megfelel a DRY kritériumnak, másrészt jól másolhatóvá teszi a metódust (`object borrowing`).

```{js}
const andris = {
  birthYear: 2015,
  calcAge = function() {
    this.age = 2021 - this.birthYear;
    return this.age
  }
}
```

Objektum metódusként nem jó arrow functiont használni, mert ebben az esetben a `this` nem az objektumra utal, hanem az azt magába foglaló kontextusból veszi, de metóduson belül jól használható, mert ebben az esetben a magába foglaló függvénytől veszi, tehát az objektumra utal.

## First-class functions

JavaScriptben a függvények maguk is értékkén viselnednek, mint minden más adattípus, vagyis bármit megtehetünk velük, amit a többi adattípussal: pl. változóba menthetjük, array-t hozhatunk létre belőlük, függvények argumentumaiként is használhatjuk őket, függvények `return` értéke lehet másik függvény is, és vannak függvény metódusok, vagyis függvényekhez mint objektumokhoz társított metódusok.

### Függvények mint argumentumok

Vannak olyan esetek, amikor függvények vagy metódusok paramétereként adunk meg egy másik függvényt. Tipikusan ilyen az Event listener, illetve több array metódus is. A megadott függvény lehet korábban deklarált (bármilyen módon), vagy anonim sima vagy arrow függvény.

```{js}
button.addEventListener('click', function(x) {})
image.addEventListener('mouseenter', highlight)

arr.forEach(callbackFun)
```

### Függvényeket eredményül adó függvények

```{js}
const greeter = function(greeting) {
  return function(name) {
    console.log(`${greeting} ${name}!`)
  }
}

const greeterHey = greeter("Hey")
greeterHey("Peter")   // Hey Peter!

greeter("Bye")("Susan")   // Bye Susan!

// Ugyanez arrow functionnel
const greet = greeting => name => console.log(`${greeting} ${name}!`)
```

### call, apply, bind

A fentiek a függvény objektumokon hívható metódusok. A `call` és az `apply` arra használhatók, hogy a függvényt meghatározott kontextushoz kötötten és megadott argumentumokkal hívjuk. Ez hasznos, ha például egy objektum metódust mentünk sima függvénybe, és ezért a `this` keyword a sima függvényhívásnál `undefined` lesz. 
A `call` és az `apply` első argumentumaként megadhatjuk azt az objektumot, amelyre a `this` mutatni fog. Ezután a `call` esetében egymás után adjuk meg az argumentumokat, az `apply` esetében pedig egy array-ben.
A `bind` ugyancsak lehetővé teszi, hogy megjelöljük, mire mutasson a `this`, például, ha a függvényt egy `class`-on belül, közvetve hívjuk. Ez azonban nem hívja a függvényt, hanem egy új függvényt ad (`return` értékként).
Ezek a függvények hasznosak lehetnak akkor is, ha egy event listenerben olyan függvényt hívunk, amely esetében azt szeretnénk, hogy a `this` ne a DOM elementre mutasson.
Ha nincs, amire a `this` mutasson, `null`-t szokás írni.

Összefoglalás: `bind` használandó, ha callback functiont akarunk megadni, `call` vagy `apply` pedig, ha azonnal futtatni akarjuk a függvényt valami más által (pl. OOP-ben a parent objektumtól öröklött property-ket létrehozni)

```{js}
cost book = lufthansa.book

book.call(eurowings, 23, 'Sarah Williams')

const flightData = [583, 'George Cooper']
book.apply(swiss, flightData)

const bookEW = book.bind(eurowings)
bookEW(23, 'Jane Doe')
// vagy
const bookEW23 = book.bind(eurowings, 23)
bookEW23('John Doe')

bookBtn.addEventListener('click', lufthansa.bookTicket.bind(lufthansa))
```

## Immediately invoked function expression

Ezek olyan függvények, amelyek azonnal és csak egyszer futnak, utána pedig nem férhetők hozzá. A függvényben létrehozott változókhoz nem lehet kívülről hozzáférni (`encapsulation`), de ehhez most már elég csak blokkot használni és let vagy const deklarációt.

```{js}
( function(...parameters) {} )(...args)
( () => {} )()
```

## Closures

A függvények azokhoz a változókhoz férhetnek hozzá, amelyeket a függvényen belül hozunk létre, argumentumokként megadunk, vagy amelyek a függvény parent scope-jainak valamelyikében hozzáférhetők. A függvényen belül deklarált függvények akkor is hozzáférnek a változókörnyezethez, ha ez utóbbi már nme fut. Ezt nevezzük `closure`-nak, és ez elsőbbséget élvez a scope chainhez képest. 