---
title: "JS libraries"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## NextAuth.js

Frontenden és backenden is használható.

Backenden [...nextAuth].js API route-okat tesz elérhetővé, ebben exportálni kell a NextAuth() függvény eredményét, amelynek argumentumként a konfigurációt adjuk meg objektumként. Ebben megadjuk a Providereket, illetve az autorizáció logikáját az authorize async metódusban. 

A front enden például a signIn függvényt importálhatjuk a bejelentkezéshez. Ennek az első argumentuma a hitelesítés módja (pl. 'credentials'), a második pedig a konfiguráció: irányítson-e át, ha sikertelen (redirect: false) és a credentialok: pl. email és password. Ez az API konfigurációban megadott metódust fogja élesíteni. 

Ha sikeres a bejelentkezés, automatikusan cookie-t ment el pl. a jwt tokennel, ha ezt a módot választottuk a konfigurációban.

Azt, hogy be vagyunk-e jelentkezve, a useSession hookkal tudjuk ellenőrizni, amely egy kételemű Array-t ad: első eleme a session, a második a loading (éppen ellenőrzi-e a bejelentkezést) Ezeket felhasználhatjuk pl. feltételes rendereléshez.

A kijelentkezéshez a signOut függvényt használhatjuk, amelynek van return értéke, de ha a useSession-t használjuk, akkor az úgy is felismeri a cookie törlését, és automatikusan újrarendereli a komponenst, immár kijelentkezett állapottal.

Route Guardot is használhatunk: ehhez szintén a useSession hookot használjuk. Ezzel az egyedüli probléma, ha ha ki vagyunk jelentkezve, akkor a loading állapot nem változik, ezért ha feltételesen renderelünk, az úgy fog maradni.

Ezt megkerülhetjük a getSession-nel: a useState-tel kezeljük a loading állapotot, illetve a sessiont, ha kell, és useEffect-tel érjük el, hogy miután renderelődött a komponens, ellenőrizze, van-e aktív jwt token. Ezt követően a state-eket használhatjuk feltételes renderelésre. 

A getSession szerveroldalon is használható, pl. a getServerSideProps-ban: ekkor argumentumként megadjuk neki, hogy 

```{js}
export async function getServerSideProps(context) {
  const session = await getSession({ req: context.req });

  if (!session)
    return {
      redirect: {
        destination: '/auth',
        permanent: false,
      },
    };

  return {
    props: { session },
  };
}
```

Ez elegánsabb, mert így nincsenek villanások.

A NextAuth egy speciális komponenset is elérhetővé tesz: a Provider komponens. A _app.js file-ban az egész appot ebbe csomagoljuk, és ennek a session propja megkaphatja az adott oldal propjai közül, amihez hozzáfér a pageProps révén a session propot, ha van.

## JWT

## bcryptjs

## Formik

## Yup

## firebase

A Firebase-zel való kommunikációt lehetővé tevő függvények.

### Autentikáció

A Firebase felületen be kell állítanunk azokat az autentikáció providereket, amelyeket használni akarunk. Szintén hozzá kell adni az alkalmazást a Firebase projekt kezelt alkalmazásaihoz, és létrehozhatunk egy Firestore vagy Realtime (régebbi) adatbázist, ahová mentjük a feliratkozottak adatait.

Az App hozzáadásánál kapunk egy kódrészletet egy config objektummal, ezt tudjuk használni a kódunkban. Az `initializeApp` ezt a konfigurációt használja, és ez teszi lehetővé, hogy a kódunk kommunikáljon a Firebase felülettel.

A bejelentkezéseket az `auth` singleton fogja kezelni, amelyet e `getAuth` függvénnyel hozunk létre.

A kódban importálhatjuk a különböző providereket (pl. Google, Facebook, Twitter, Github, stb.) és a különböző bejelentkezési módokat (pl. Popup, Redirect, stb.). Ezek segítségével létrehozhatjuk a saját bejelentkeztető függvényeinket, amelyek az `auth` singletont és a létrehozott provider instanciákat használják.


```{js}
import { initializeApp } from 'firebase/app';
import {
  getAuth,
  signInWithRedirect,
  signInWithPopup,
  GoogleAuthProvider,
} from 'firebase/auth';

const firebaseConfig = {
  apiKey: 'AIzaSyBC_W4cXAfniGPYZptBEegtcS2J5j1YrpE',
  authDomain: 'crwn-clothing-6f32d.firebaseapp.com',
  projectId: 'crwn-clothing-6f32d',
  storageBucket: 'crwn-clothing-6f32d.appspot.com',
  messagingSenderId: '223021382295',
  appId: '1:223021382295:web:b9f803aac768ef321a07d2',
};

const firebaseApp = initializeApp(firebaseConfig);

const googleProvider = new GoogleAuthProvider();
googleProvider.setCustomParameters({
  prompt: 'select_account',
});

export const auth = getAuth();

export const signInWithGooglePopup = () =>
  signInWithPopup(auth, googleProvider);
export const signInWithGoogleRedirect = () =>
  signInWithRedirect(auth, googleProvider);
```

signInWithRedirect esetén, mivel ez elirányít, ezért amikor visszatérünk, újramountol - elveszik a state.

Ezért ehhez külön használni kell useEffect-ben a getRedirectResult függvényt, amely paraméterként az auth singletont kapja meg, és ez az első renderelésnél fusson és ebből hozzáférhetünk a szükséges adatokhoz:

```{jsx}
import { getRedirectResult } from 'firebase/auth';

// Own util functions
import { 
  signInWithGoogleRedirect,
  createUserDocumentFromAuth 
} from '../../utils/firebase/firebase.utils';

// ...

const SignIn = () => {
  useEffect(() => {
      const getRedirectResponse = async () => {
        const response = await getRedirectResult(auth);
        if (response) {
          const userDocRef = await createUserDocumentFromAuth(response.user);
        }
      };
      getRedirectResponse();
    }, []);
  
  
  // ...
  return (
    <div>
      <h1>Sign in page</h1>
      {/* <button onClick={signInWithGoogleRedirect}>
        Sign in with Google Redirect
      </button> */}
    </div>
  );
}

```