---
title: "JavaScript alapok"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## JavaScript használata a böngészőben

A böngészők képesek futtatni a JavaScript kódokat. Ehhez JavaScript engine-t használnak, amely a JS kódot lefordítja gépi kódra. A legismertebb a Google V8 engine-je, amelyet a Node.js is használ. 

A böngészőben való használathoz az adott JS scriptet az adott html oldalhoz kell csatolni a <script> tag használatával. Lehetőség van közvetlenül a html file-ban JS parancsokat megadni, ha azok rövidek, de jobb a külső file használata.

A <script> kerülhet a <body> rész végére, de jobb a <head>-be illesztett <script>, amely esetben viszont a `defer` tulajdonságot hozzá kell adni, hogy a parancsok csak az oldal betöltése után fussanak le. 

Ha több scriptet is használunk, akkor először azokat kell beilleszteni (pl. külső scriptek), amelyekre a többi támaszkodik. Ez csak a `defer` módszerrel működik.

Ha nincs interakció a scriptek között, az `async` tulajdonság hozzáadása is működőképes (pl. Google Analytics)

A `defer` és `async` HTML5 funkció, a régi böngészők csak a body végére illesztett scripteket tudják kezelni.

## A JS működése

A V8 engine beolvassa a JS kódot és faszerű struktúrát alkot belőle, amelyben részekre bontja a kódot. Ezután az interpreter lefordítja a processzor által is érthető nyelvre. Futás közben a profiler vizsgálja a kódot, és ha lehetséges, átadja a compilernek, amely optimalizálja, és az eredetileg futó kódot az optimalizáltra cseréli. Ez a folyamat ismétlődik valahányszor optimalizálási lehetőség adódik. 

A JS nyelv szabályait az ECMAScript standardek adják meg. Nagy lépés volt az ES6 kifejlesztése, amely sok funkcióval bővítette a JS nyelvet. 

## Változónevek 

JavaScriptben a változóneveknek hasonló szabályoknak kell megfelelniük, mint más programnyelvekben:  

- nem kezdődhetnek számmal
- csak kis- és nagybetűket, számokat, _ és $ karaktereket tartalmazhatnak
- nem egyezhetnek `reserved keyword`-ökkel

Jó gyakorlatok, íratlan szabályok:  

- camelCase változónevek
- KONSTANS_NEVEK nagybetűvel, `_`-sal
- beszédes nevek

## Kommentelés

JavaScriptben egysoros kommenteket `//` után, többsoros kommenteket pedig `/*` és `*/` közé írva tudunk beilleszteni.

```{js}
// This will not run.
// console.log("Hello World")

/*
This is a multiline comment
that goes on and on and on
an on.
*/
```

## Változók deklarálása

Amikor létrehozunk egy változót, `let` vagy `const`, régebben `var` (pre ES6) utasítással deklaráljuk.  
Van lehetőség üres változót is létrehozni, amelyet később rendelünk hozzá értékhez (ebben az esetben csak `let` használható, `const` nem).  
A `const` paranccsal létrehozott változó később nem rendelhető más értékhez (nem mutálható), de ha az értéke `Array` vagy más objektum, akkor ez utóbbi mutálható marad. Ennek oka, hogy a primitív értékek a `call stack`-ben vannak tárolva, de az objektumok a `memory heap`-ben a JS engine-on belül, és a változónév az objektumra mutató referenciához van rendelve, nem pedig magához az objektumhoz. Ha az objektum változik, akkor minden változó, amely erre mutatott szintén megváltozik.

Ha azt szeretnénk, hogy az objektum ne legyen változtatható, az `Object.freeze()` metódust használhatjuk, amely azonban csak az első szintet teszi módosíthatatlanná, a mélyebben beágyazódó adatok módosíthatók. Ha mélyebben is rögzíteni akarjuk az objektum tartalmát, külső csomagokat kell használni.

A `let` és a `var` abban különbözik, hogy előbbi, ha ciklusban, függvényben, vagy bármilyen blokkban használjuk, helyi hatókörben hoz létre változót, míg a `var` a függvény hatókörében hoz létre változót, amiből bonyodalmak származhatnak.  
Miután létrehoztunk egy változót, már nem kell újra használni a `let`, `const` parancsokat, csak egyszerűen hozzárendelni az új értéket a változóhoz (`=`). Ha ismét használjuk a `let` vagy `const` parancsot, akkor új változót hozunk létre az adott `scope`-ban (blokkban), ugyanolyan névvel, de más hatókörben.
  
A JavaScript az értékek típusát automatikusan megállapítja. A változónevet (kivéve `const`-tal létrehozottat) később más típusú változóhoz is hozzárendelhetjük.  
  
A változó típusát a `typeof` paranccsal kapjuk meg. Az alaptípusok:  

1. number - számok (egész és tizedes is)
2. string
3. boolean - true és false

További típusok:  

4. undefined - üres érték
5. null
6. symbol
7. bigInt

```{js}
let myAge = 34;
myAge = "too much"   // Dynamic typing és már nem kell let
let year;   // Üres változó: value = undefined, type = undefined

const birthYear = 1986;
birthYear = 86   // Hiba: nem változtatható

//De:
const friends = ["John", "Peter", "Kate"]
friends[1] = "Jim"

//De:
friends = ["Susan", "Tom", "Bob"]  // Error

console.log(typeof myAge)
```

## Alapműveletek

1. Matematikai műveletek: `+ - * / ** %`
2. Hozzárendelés: `= += -= *= /= %= **= ++ --`
3. Összehasonlítás: `< > <= >= == === != !==`
4. Logikai operátorok: `&& || !`

## Típuskonverzió és koerció

Konverzió: explicit pl. Number() vagy String()
Koreció: implicit:  

- A `+` a számokat is szöveggé alakítja, ha vegyesen használjuk
- A `-`, `*`, `<>`, stb. számmá alakítja a szövegként tárolt számot

## Template literal

Ha szövegeket és értékeket akarunk kombinálni, a legjobb megoldás a template literal használata:
```{js}
console.log(`My name is ${name}, and I'm a ${2021 - birthYear} year old ${profession}.`)

console.log(`This is, how
I print a 
multiline string.`)
```

## Változók másolása

Ha sima primitív változót másolunk, akkor az új változó a régi értékét kapja (mert ezeket a `call stackben` tárolja):

```{js}
const a = 12;
const b = a;
a = 15;
console.log(b)    // 12
```

De ha objektumot (`reference type`) rendelünk új változónévhez, akkor nem az értéket kapja, hanem ugyanarra a memóriahelyre fog mutatni a `memory heapben`. Ha megváltoztatjuk az eredetit, az új is megváltozik (ld. Pythonban is)

```{js}
const old = {
  name: "John Doe",
  age: 30
};

const new = old;
new.age = 27;
console.log(old.age);    // 27
```

Ezért van az, hogy a const-tal létrehozott objektumok tartalmát módosíthatjuk, de nem oszthatjuk ki újra a változónevet másik objektumnak.

### Objektumok és array-ek másolása

```{js}
const objCopy = Object.assign({}, oldObj)   // shallow copy!
const arrCopy = [...oldArr]
const arrCopy = oldArr.slice()
```