---
title: "Redux"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

A Redux arra szolgál, hogy az alkalmazás state-jét kezelje. Fő összetevői:  

1. `store`, amely a `state` objektumot tárolja, 
2. egy `root-reducer` függvény, opcionálisan több sima `reducer` függvénnyel, amely az akció függvényében változtatja a state-et,
3. egy vagy több `action creator` függvény, amellyel különböző akciók hozhatók létre

## Reducer függvények

Ez a része tulajdonképpen megfelel a React alap reducer logikájának, a reducerek alig változnak ahhoz képest. Egy változás, hogy a sima React `useReducer`-nél ez utóbbi megkapja a kezdőállapotot, amit a reducer függvény használ, itt viszont a kezdőállapotot a reducer függvény deklarációjában kell megadni default értékként. Ezt használja az inicializálás során, később pedig megkapja az aktuális state-et.

A másik különbség, hogy a Redux esetében minden reducer megkap minden action-t, és ezért ha az adott reducer nem is tudja kezelni az action-t, akkor se hibát dobunk, hanem a state-et adjuk vissza, és így a program tudja, hogy ez a reducer nem változtatta a state-et, hiszen nem egy új objektumot kap.

## Store





## Action creator függvények


Lépések: 
1. Opcionális: Létrehozni egy alapértelmezett `state`-et: objektum a szükséges property-kkel. A state létrehozható a reducer részeként is, és lehet egyszerűbb is, mint egy komplex objektum: akár egyetlen érték vagy egy üres array.
2. Létrehozni egy vagy több `reducer` függvényt, amely a state-et változtatja (valójában új state-et ad). A reducer tiszta függvény, mellékhatások nélkül. Két paramétert kap: a jelenlegi state-et és egy actiont. Sokszor switch-et használnak, hogy többféle típusú actiont kezelni tudjon. Return értéke egy új vagy az eredeti state.
3. A `store` a `Redux.createStore()` révén jön létre (nevesítve is importálhatjuk), amely a reducer függvényt kapja paraméterként.
4. Opcionális: Létrehozni az `action creator` fügvényeket, amelyek objektumokat (`action`-öket) adnak, amelyek kötelező property-je a típus (`type`). Az action objektumok közvetlenül is hozzáadhatók a dispatch metódushoz.

Opcionális best practice:  

- Az action típusokat lehetséges konstans változóként létrehozni (nagybetűs név), és a függvényekben ezekre hivatkozni, nem pedig stringeket használni, hogy elkerüljük az elgépeléseket. Hogy áttekinthetőbb legyen, ezek egy objektum property-jeiként is létrehozhatók.
- A state összes elemét egyetlen store-ban kell kezelni, de ehhez lehetséges több reducer függvényt írni és kombinálni, amelyek a state különböző alkotórészeit kezelik.


```{js}
// Konstansok
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';

// State objektum
const defaultState = {
  authenticated: false
  notes: []
};

// Reducer függvények
const authReducer = (state = { authenticated: false }, action) => {
  switch (action.type) {
    case LOGIN:
      return { authenticated: true }
    case LOGOUT:
      return { authenticated: false }
    default:
      return state
  }
};

const notesReducer = (state = { notes: [] }, action) => {
  switch (action.type) {
    case 'ADD':
      return { notes: [...notes, action.note] }
    case 'REMOVE':
      return { notes.filter(note => note.id !== action.note.id) }
    default:
      return state
  }
};

const rootReducer = Redux.combineReducers({
  authenticated: authReducer,
  notes: notesReducer
})

// Store - csak egy reducert fogad el
const store = Redux.createStore(rootReducer);

// Action creatorok - az action-ök közvetlenül is küldhetők
const loginUser = () => {
  return {
    type: LOGIN
  }
};

const logoutUser = () => {
  return {
    type: LOGOUT
  }
};
```

## Store metódusok

```{js}
const currentState = store.getState()   // Get current state
store.dispatch(action)                  // Dispatch an action to the store
store.subscribe(callback)               // Call callback fun every time store gets updated
```

## Aszinkron műveletek

Erre a célra a Redux beépített middleware-jét használhatjuk. A store létrehozásánál második argumentumként adjuk meg a reducer függvény mellett (ld. lent). Az alábbi példában az időzítés jelenti az aszinkron folyamatot, de ez lehet API request is.

Ilyenkor szokás az aszinkron folyamat indítása előtt egy actiont élesíteni, amely jelzi, hogy az adatok lekérése folyamatban van (pl. ikonnal), majd az adatok beérkezése után egy újabb actiont, amely szállítja a kapott adatokat. Az action creator egy `dispatch` argumentummal ellátott függvényt ad, amelyben élesítjük a két akciót, hogy ezt lehetővé tegye.

```{js}
// Konstans
const REQUESTING_DATA = 'REQUESTING_DATA'
const RECEIVED_DATA = 'RECEIVED_DATA'

// Action creator
const requestingData = () => { return {type: REQUESTING_DATA} }
const receivedData = (data) => { return {type: RECEIVED_DATA, users: data.users} }

const handleAsync = () => {
  return function(dispatch) {
    // Dispatch request action here
    dispatch(requestingData())
    setTimeout(function() {
      let data = {
        users: ['Jeff', 'William', 'Alice']
      }
      // Dispatch received data action here
      dispatch(receivedData())
    }, 2500);
  }
};

// Initial state
const defaultState = {
  fetching: false,
  users: []
};

// Reducer függvény
const asyncDataReducer = (state = defaultState, action) => {
  switch(action.type) {
    case REQUESTING_DATA:
      return {
        fetching: true,
        users: []
      }
    case RECEIVED_DATA:
      return {
        fetching: false,
        users: action.users
      }
    default:
      return state;
  }
};

const store = Redux.createStore(
  asyncDataReducer,
  Redux.applyMiddleware(ReduxThunk.default)
);
```

## Immutabilitás

Reduxban fontos, hogy a state-et ne mutáljuk, hanem mindig új state-et adjunk vissza. Ez számok és stringek esetében nem probléma, hiszen ezek eleve mutálhatatlanok, array és objektum state-ek esetében viszont erre nekünk kell odafigyelni, és az eredeti objektum másolatához hozzáfűzni az új adatokat / a másolatot módosítani.

### Megoldási lehetőségek

Ha csak egyszintes a state, akkor a spread operátor ([...arr])jól használható, hiszen másolatot ad.
Törlésre használható a `.slice`, kombinálva a spread operátorral vagy `.concat`-tal
Szintén használhatók a `.map` és `.filter` metódusok, amelyek új array-t adnak.
Objektum másolására az `Object.assign()` használható, amely első paramétere jellemzően egy üres objektum, a további paraméterek pedik azok az eredeti objektumok, amelyek tulajdonságaival fel szeretnénk tölteni.

## Redux Toolkit

